In [1]:
#filename = 'outputs/mpt_mc_0304_test.pkl'  # Replace this with the path to your file
filename = 'outputs/test.pkl'

In [2]:
import pickle
import pandas as pd

# Load the pickle file
with open(filename, 'rb') as f:
    output = pickle.load(f)

# Extract the data and create a structured DataFrame
for era, data in output['cutflow'].items():
    print(f"Era: {era}")
    
    # Check if data is not empty
    if not data:
        print("No data available for this era.")
        continue
    
    # Separate the entries into 'gen' and 'reco' based on the keys
    gen_data = {}
    reco_data = {}
    first_key = next(iter(data))  # Retrieve the first key safely
    for key, value in data[first_key].items():
        if 'gen' in key or 'Gen' in key:
            gen_data[key] = value
        elif 'reco' in key or 'Reco' in key:
            reco_data[key] = value
        else:
            # Include keys without 'gen' or 'reco' in both tables for reference
            gen_data[key] = value
            reco_data[key] = value
    
    # Convert to DataFrames
    gen_df = pd.DataFrame(list(gen_data.items()), columns=['Cut', 'Gen Count'])
    reco_df = pd.DataFrame(list(reco_data.items()), columns=['Cut', 'Reco Count'])
    
    # Merge the two dataframes
    cutflow_df = pd.merge(gen_df, reco_df, on="Cut", how="outer").fillna("")

    # Display the DataFrame in tabular format
    display(cutflow_df)

Era: UL18NanoAODv9

                        Cut    Gen Count   Reco Count
0                      sumw  2973.467529  2973.467529
1                all events     399514.0     399514.0
2               weights cut     383511.0     383511.0
3                       npv     383511.0     383511.0
4                 oneGenJet     375811.0
..                      ...          ...          ...
56  z_jet_dphi_sel_reco_seq                   39302.0
57   z_pt_asym_sel_reco_seq                   30290.0
58              presel_reco                   30878.0
59              allsel_reco                   29512.0
60             matched_reco                  304462.0

[61 rows x 3 columns]

In [3]:
cf = output['cutflow']

In [4]:
for era in cf.keys():
    for ht in cf[era].keys():
        print(era)
        print(ht)
        d = cf[era][ht]
        # print( 'oneGenJet_seq', d[ 'oneGenJet_seq'] )
        # print( 'twoGen_leptons_seq', d[ 'twoGen_leptons_seq'] )
        # print( 'z_ptcut_gen_seq', d[ 'z_ptcut_gen_seq'] )
        # print( 'z_mcut_gen_seq', d[ 'z_mcut_gen_seq'] )
        # print(  'z_jet_dphi_sel_gen_seq', d[ 'z_jet_dphi_sel_gen_seq'] )
        # print( 'z_pt_asym_sel_gen_seq', d[ 'z_pt_asym_sel_gen_seq'] )
        print(d['all events'])
        print(  d[ 'oneGenJet_seq'] )
        print(  d[ 'oneGenJet_seq'] )
        print(  d[ 'twoGen_leptons_seq'] )
        print(  d[ 'z_ptcut_gen_seq'] )
        print( d[ 'z_mcut_gen_seq'] )
        print(  d[ 'z_jet_dphi_sel_gen_seq'] )
        print(  d[ 'z_pt_asym_sel_gen_seq'] )

UL18NanoAODv9
DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
399514
375811
375811
99845
74778
69017
66893
51473

In [5]:
cf[era].keys()

dict_keys(['DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8'])

In [6]:
sorted_era = ['DYJetsToLL_M-50_HT-100to200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8',
              'DYJetsToLL_M-50_HT-200to400_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8',
              'DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8',
              'DYJetsToLL_M-50_HT-600to800_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8',
              'DYJetsToLL_M-50_HT-800to1200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8',
              'DYJetsToLL_M-50_HT-1200to2500_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8',
              'DYJetsToLL_M-50_HT-2500toInf_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8'
             ]

In [7]:
for era in cf.keys():
    print(era)
    for ht in sorted_era:
        
        print(ht)
        if ht in cf[era].keys():
            d = cf[era][ht]
            # print( 'oneGenJet_seq', d[ 'oneGenJet_seq'] )
            # print( 'twoGen_leptons_seq', d[ 'twoGen_leptons_seq'] )
            # print( 'z_ptcut_gen_seq', d[ 'z_ptcut_gen_seq'] )
            # print( 'z_mcut_gen_seq', d[ 'z_mcut_gen_seq'] )
            # print(  'z_jet_dphi_sel_gen_seq', d[ 'z_jet_dphi_sel_gen_seq'] )
            # print( 'z_pt_asym_sel_gen_seq', d[ 'z_pt_asym_sel_gen_seq'] )
            
            print(  'all events', d[ 'all events'] )
    
            # print(  'oneRecoJet', d[ 'oneRecoJet'] )
            # print( 'twoReco_leptons',  d[ 'twoReco_leptons'] )
            # print( 'z_ptcut_reco',  d[ 'z_ptcut_reco'] )
            # print( 'z_mcut_reco', d[ 'z_mcut_reco'] )
            # print(  'z_jet_dphi_sel_reco', d[ 'z_jet_dphi_sel_reco'] )
            # print(  'z_pt_asym_sel_reco',d[ 'z_pt_asym_sel_reco'] )
    
    
            print('all events', d[ 'all events'] )
            print(  d[ 'oneRecoJet_seq'] )
            print(  d[ 'twoReco_leptons_seq'] )
            print(  d[ 'z_ptcut_reco_seq'] )
            print( d[ 'z_mcut_reco_seq'] )
            print(  d[ 'z_jet_dphi_sel_reco_seq'] )
            print(  d[ 'z_pt_asym_sel_reco_seq'] )
            print(  d[ 'jetid_seq'] )
    
            # print( d[ 'all events'], d[ 'oneGenJet_seq'], d[ 'oneRecoJet_seq']  )
            # print( 'twoGen_leptons_seq', d[ 'twoGen_leptons_seq'] )
            # print( 'z_ptcut_gen_seq', d[ 'z_ptcut_gen_seq'] )

UL18NanoAODv9
DYJetsToLL_M-50_HT-100to200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
DYJetsToLL_M-50_HT-200to400_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
DYJetsToLL_M-50_HT-400to600_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
all events 399514
all events 399514
303761
55266
43771
40210
39302
30290
0
DYJetsToLL_M-50_HT-600to800_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
DYJetsToLL_M-50_HT-800to1200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
DYJetsToLL_M-50_HT-1200to2500_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8
DYJetsToLL_M-50_HT-2500toInf_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8

In [8]:
# missed = output['misses_u'].project('ptgen', 'mgen')

# passed = output['response_matrix_u'].project('ptgen', 'mgen')

# import matplotlib.pyplot as plt
# plt.stairs(missed[0, :].values()/(passed[0,:].values()+missed[0, :].values()), missed[0, :].axes[0].edges, label = 'pt 200-260 GeV')
# plt.stairs(missed[1, :].values()/(passed[1,:].values()+missed[1, :].values()), missed[0, :].axes[0].edges, label = 'pt 260-350 GeV')
# plt.stairs(missed[2, :].values()/(passed[2,:].values()+missed[2, :].values()), missed[0, :].axes[0].edges, label = 'pt 350-460 GeV')
# plt.stairs(missed[3, :].values()/(passed[3,:].values()+missed[3, :].values()), missed[0, :].axes[0].edges, label = 'pt 460- GeV')
# plt.xlim(0,200)
# plt.title("Not Reconstructed Events/Total GEN events passing selections ")
# plt.ylabel("Missed/Total (sum of weights)")
# plt.xlabel("Jet mass")
# plt.legend()

In [9]:
prependstr = f'outputs/cutflow_csvs/'

In [10]:
import csv
import re

for era in cf.keys():
    # Open a new CSV file for each era
    with open(prependstr+f'{era}_cut_counts.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        
        # Write the headers, including the new Ratio column
        writer.writerow(['HT-Bin', 'Cut Name', 'RECO Level Cutflow', 'Gen Level Cutflow', 'RECO/GEN Ratio'])
        
        for ht in sorted_era:
            if ht in cf[era].keys():
                d = cf[era][ht]
                
                # Extract the HT range (e.g., 100to200) using regex
                ht_bin = re.search(r'HT-(\d+to\d+|\d+toInf|Inf)', ht)
                ht_bin_text = ht_bin.group(1) if ht_bin else "Unknown"
                
                # List of cuts with 'all events' at the top
                cuts = [
                    ('All Events', 'all events', 'all events'),  # 'all events' at the top
                    ('Jet cuts', 'oneRecoJet', 'oneGenJet'),
                    ('Lepton Cuts', 'twoReco_leptons', 'twoGen_leptons'),                
                    ('Two electron & both passing pfRelIso_03', 'z_ptcut_reco', 'z_ptcut_gen'),
                    ('Z object pt cut', 'z_ptcut_reco', 'z_ptcut_gen'),
                    ('Z object pt cut', 'z_ptcut_reco', 'z_ptcut_gen'),
                    ('Z object m cut', 'z_mcut_reco', 'z_mcut_gen'),
                    ('Dphi(Z, jet) > 1.57', 'z_jet_dphi_sel_reco', 'z_jet_dphi_sel_gen'),
                    ('pt assymetry cut', 'z_pt_asym_sel_reco', 'z_pt_asym_sel_gen')
                ]
                
                # Write each cut to the CSV with an empty ratio column
                for cut_name, reco_key, gen_key in cuts:
                    writer.writerow([ht_bin_text, cut_name, d[reco_key], d[gen_key], ""])
                
                # Special case for Jet ID and Final counts
                writer.writerow([ht_bin_text, 'JetID', d['jetid'], 0, ""])  # Jet ID applied only to RECO, so GEN gets 0
                
                # Calculate the ratio for Final counts row
                final_reco = d['jetid_seq']
                final_gen = d['z_pt_asym_sel_gen_seq']
                ratio = final_reco / final_gen if final_gen != 0 else "Undefined"
                
                # Write Final counts row with the calculated ratio
                writer.writerow([ht_bin_text, 'Final counts', final_reco, final_gen, ratio])

In [11]:
import csv
import re

for era in cf.keys():
    # Open a new CSV file for each era
    with open(prependstr+f'{era}_cutflow.csv', mode='w', newline='') as file:
        writer = csv.writer(file)
        
        # Write the headers, including the new Ratio column
        writer.writerow(['HT-Bin', 'Cut Name', 'RECO Level Cutflow', 'Gen Level Cutflow', 'RECO/GEN Ratio'])
        
        for ht in sorted_era:
            if ht in cf[era].keys():
                d = cf[era][ht]
                
                # Extract the HT range (e.g., 100to200) using regex
                ht_bin = re.search(r'HT-(\d+to\d+|\d+toInf|Inf)', ht)
                ht_bin_text = ht_bin.group(1) if ht_bin else "Unknown"
                
                # List of cuts with 'all events' at the top
                cuts = [
                    ('All Events', 'all events', 'all events'),  # 'all events' at the top
                    ('Jet cuts', 'oneRecoJet_seq', 'oneGenJet_seq'),
                    ('Lepton cuts', 'twoReco_leptons_seq', 'twoGen_leptons_seq'),                
                    #('Two electron & both passing pfRelIso_03', 'z_ptcut_reco_seq', 'z_ptcut_gen_seq'),
                    ('\PZ $p_T$ cut', 'z_ptcut_reco_seq', 'z_ptcut_gen_seq'),
                    ('\PZ $m$ cut', 'z_mcut_reco_seq', 'z_mcut_gen_seq'),
                    ('$\Delta \phi$ (Z, jet) > 1.57', 'z_jet_dphi_sel_reco_seq', 'z_jet_dphi_sel_gen_seq'),
                    ('$p_{T,asym$}', 'z_pt_asym_sel_reco_seq', 'z_pt_asym_sel_gen_seq')
                ]
                
                # Write each cut to the CSV with an empty ratio column
                for cut_name, reco_key, gen_key in cuts:
                    writer.writerow([ht_bin_text, cut_name, d[reco_key], d[gen_key], ""])
                
                # Special case for Jet ID and Final counts
                #writer.writerow([ht_bin_text, 'JetID', d['jetid'], 0, ""])  # Jet ID applied only to RECO, so GEN gets 0
                
                # Calculate the ratio for Final counts row
                final_reco = d['z_pt_asym_sel_reco_seq']
                final_gen = d['z_pt_asym_sel_gen_seq']
                ratio = final_reco / final_gen if final_gen != 0 else "Undefined"
                
                # Write Final counts row with the calculated ratio
                writer.writerow([ht_bin_text, 'Final counts', final_reco, final_gen, f"{ratio:.2f}"])

In [12]:
import pandas as pd

# Load CSV
df = pd.read_csv('outputs/cutflow_csvs/UL18NanoAODv9_cut_counts.csv')

# Change pandas display settings to show all rows
pd.set_option('display.max_rows', None)

# Display the entire DataFrame
df

,HT-Bin,Cut Name,RECO Level Cutflow,Gen Level Cutflow,RECO/GEN Ratio
0,400to600,All Events,399514,399514,NaN
1,400to600,Jet cuts,303761,375811,NaN
2,400to600,Lepton Cuts,67562,102341,NaN
3,400to600,Two electron & both passing pfRelIso_03,50994,75918,NaN
4,400to600,Z object pt cut,50994,75918,NaN
5,400to600,Z object pt cut,50994,75918,NaN
6,400to600,Z object m cut,62487,94960,NaN
7,400to600,"Dphi(Z, jet) > 1.57",197727,286624,NaN
8,400to600,pt assymetry cut,45391,95392,NaN
9,400to600,JetID,0,0,NaN
10,400to600,Final counts,0,51473,0.0

In [13]:
import pandas as pd

# Load CSV
df = pd.read_csv('outputs/cutflow_csvs/UL18NanoAODv9_cutflow.csv')

# Change pandas display settings to show all rows
pd.set_option('display.max_rows', None)

# Display the entire DataFrame
df

,HT-Bin,Cut Name,RECO Level Cutflow,Gen Level Cutflow,RECO/GEN Ratio
0,400to600,All Events,399514,399514,NaN
1,400to600,Jet cuts,303761,375811,NaN
2,400to600,Lepton cuts,55266,99845,NaN
3,400to600,\PZ $p_T$ cut,43771,74778,NaN
4,400to600,\PZ $m$ cut,40210,69017,NaN
5,400to600,"$\Delta \phi$ (Z, jet) > 1.57",39302,66893,NaN
6,400to600,"$p_{T,asym$}",30290,51473,NaN
7,400to600,Final counts,30290,51473,0.59